# Generated by Django 3.2.13 on 2022-11-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('overview', models.TextField()),
                ('rate', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('release_date', models.DateField()),
                ('poster_path', models.CharField(max_length=50)),
                ('tmdb_id', models.IntegerField()),
                ('genre', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
